#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		echo
		pwd
		echo "FAILED"
		echo
		exit 1
	fi
}

# check that data files exist
if [[ -f data/reaclib_db && -f data/nuclide_db ]]; then
    echo "nuclib and reaclib databases exist"
else
    echo "I require the nuclib and reaclib databases; fetching them now"
    ./install_data
    check_okay
fi

cd make; make
check_okay
cd ../test/make; make
check_okay
cd ..
./tester |tee test_output
check_okay
cd ..
