#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		echo
		pwd
		echo "FAILED"
		echo
		exit 1
	fi
}

echo
echo "======================"
echo "BUILDING NETJINA TOOLS"
echo "======================"
echo

# install data files
./install_data

echo
echo "Building libraries"
echo "------------------"
cd make; make
check_okay

echo
echo "Testing"
echo "-------"
cd ../test/make; make
check_okay
cd ..
./tester |tee test_output
check_okay
cd ..
echo "finished. compare test/test_output with test/sample output"
echo
