#!/bin/bash

function check_okay {
    if [ $? -ne 0 ]; then
        echo
        pwd
        echo "FAILED"
        echo
        exit 1
    fi
}

#databases
RLIB=reaclib_db
NLIB=nuclib_db

#temporary files
TMP_RLIB="tmp_$RLIB"
TMP_NLIB="tmp_$NLIB"

#compression suffic
ZIP='.gz'
UNZIP=`which gunzip`

#locations
RLIB_URL=https://dl.dropboxusercontent.com/u/52649885/netJina/20140508default2.gz
NLIB_URL=https://dl.dropboxusercontent.com/u/52649885/netJina/winvne_v2.0.dat.gz

mkdir -p data
check_okay
echo "fetching $NLIB from $RLIB_URL"
cd data
curl -o $TMP_RLIB$ZIP $RLIB_URL
check_okay

echo "unpacking data"
$UNZIP $TMP_RLIB$ZIP
check_okay

# now move to final location, prompt if overwrite
mv -i $TMP_RLIB $RLIB

echo "fetching $NLIB from $NLIB_URL"

curl -o $TMP_NLIB$ZIP $NLIB_URL
check_okay

echo "unpacking data"
$UNZIP $TMP_NLIB$ZIP
check_okay

# now move to final location, prompt if overwrite
mv -i $TMP_NLIB $NLIB
echo "done"
echo

cd ..
