#!/usr/bin/env bash

function show_help {
	echo "usage: $(basename "$0") $USAGE"
	echo
	echo "$LONG_USAGE"
	exit 0
}

function check_okay {
    if [ $? -ne 0 ]; then
        echo
        echo "installation failed..."
        exit 1
    fi
}

USAGE="[(-d|--directory) </path/to/top-level>]"
LONG_USAGE="With -d or --directory option, installs netJina libraries in </path/to/top-level/lib> and Fortran include (*.mod) files in </path/to/top-level/include>.  If no option is given, the <top-level> directory is taken to be the current one."

THISDIR=`pwd`
ROOTDIR=$THISDIR
LIBDIR=""
MODDIR=""
DATADIR=""

LIBS="libnetJina.a"
MODS=(  netjina_bdat.mod
        netjina_def.mod
        netjina_io.mod
        netjina_lib.mod
        netjina_storage.mod )
DATA_DBS=(  reaclib_db
            nuclib_db )

# process options
case "$1" in
    -h|--help)
	show_help
esac

while case "$#" in 0) break ;; esac
do
    case "$1" in
        -d|--directory)
        shift
        ROOTDIR="$1"
        ;;
    esac
    shift
done
    
LIBDIR=$ROOTDIR/lib
MODDIR=$ROOTDIR/include
DATADIR=$ROOTDIR/data

./build_and_test

echo
echo "Installing files"
echo "----------------"
if [ ! -d $LIBDIR ]; then
    echo "making $LIBDIR"
    mkdir -p $LIBDIR
    check_okay
fi

echo "installing $LIBS to $LIBDIR..."
cp make/$LIBS $LIBDIR
check_okay

if [ ! -d $MODDIR ]; then
    echo "making $MODDIR"
    mkdir -p $MODDIR
    check_okay
fi

echo "installing ${MODS[*]} to $MODDIR"
for src in ${MODS[*]}; do
    cp make/$src $MODDIR
    check_okay
done

if [ $ROOTDIR != $THISDIR ]; then
    echo "installing ${DATA_DBS[*]} to $DATADIR"
    if [ ! -d $DATADIR ]; then
        echo "making $DATADIR"
        mkdir -p $DATADIR
        check_okay
    fi
    for src in ${DATA_DBS[*]}; do
        cp data/$src $DATADIR
        check_okay
    done
fi

echo
echo "======================"
echo "Installation finished."
echo "======================"
echo
